Section "ServerLayout"
    Identifier "DefaultLayout"
    Screen "Screen0"
EndSection

Section "Device"
    Identifier "Framebuffer"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device "Framebuffer"
    DefaultDepth 16
    Subsection "Display"
        Depth 16
        Modes "480x320"
    EndSubsection
EndSection